FROM golang:1.14 as builder

ARG ENV
ARG PWD

ENV GO111MODULE=on
ENV ENV=${ENV:-dev}

WORKDIR /go/src/
ADD ./ ./app/

WORKDIR /go/src/app
RUN go mod download || true; \
    make all

FROM gcr.io/distroless/base

ARG HOSTNAME
ARG LISTEN

EXPOSE $LISTEN

ENV HOSTNAME $HOSTNAME
ENV LISTEN $LISTEN
ENV ENV $ENV

COPY --from=builder /go/src/app/bin/app /bin/littr
ADD ./templates /
ADD ./assets /

ADD docker/app/.env ./
ADD docker/app/.env.dev ./

CMD ["/bin/littr"]

