FROM golang:1.14 as builder

ARG ENV

ENV GO111MODULE=on
ENV ENV=${ENV:-dev}

WORKDIR /go/src/
ADD ./ ./app/

WORKDIR /go/src/app
RUN go mod download || true; \
    make all

FROM gcr.io/distroless/base

ARG HOSTNAME=brutalinks
ARG PORT=3003

EXPOSE $PORT

ENV HOSTNAME $HOSTNAME
ENV PORT $PORT
ENV ENV $ENV

COPY --from=builder /go/src/app/bin/app /bin/littr
ADD ./templates /templates
ADD ./assets /assets

ADD docker/app/.env ./
ADD docker/app/.env.dev ./

CMD ["/bin/littr"]
