FROM golang:1.15 as builder

ARG ENV
ARG HOSTNAME

ENV GO111MODULE=on
ENV ENV=${ENV:-dev}

WORKDIR /go/src/
ADD ./ ./app/

WORKDIR /go/src/app
RUN go mod download || true; \
    make all && \
    docker/gen-certs.sh app

FROM gcr.io/distroless/base

ARG HOSTNAME
ARG PORT

ENV ENV ${ENV:-dev}
ENV LISTEN_HOSTNAME ${HOSTNAME:-brutalinks}
ENV LISTEN_PORT ${PORT:-3003}
ENV KEY_PATH=/etc/ssl/certs/app.key
ENV CERT_PATH=/etc/ssl/certs/app.crt
ENV HTTPS=true

EXPOSE ${PORT:-3003}

VOLUME /.env
VOLUME /storage

COPY --from=builder /go/src/app/*.key /go/src/app/*.crt /go/src/app/*.pem /etc/ssl/certs/
COPY --from=builder /go/src/app/bin/app /bin/app
ADD ./templates /templates
ADD ./assets /assets
ADD ./README.md /README.md

CMD ["/bin/app"]
