image: archlinux
packages:
  - go
  - postgresql
sources:
  - https://github.com/mariusor/littr.go
environment:
  GO111MODULE: 'on'
secrets:
  - 32610757-76e9-4671-adf1-98163ca8b594
tasks:
  - setup: |
      set +x
      sudo -u postgres -- initdb --locale en_US.UTF-8 -E UTF8 -D /var/lib/postgres/data
      sudo systemctl start postgresql.service
      cd littr.go && go mod download
  - versions: |
      set +x
      $(readlink -f /proc/$$/exe) --version | head -n1
      pg_ctl --version
      make --version | head -n1
      go version
  - build: |
      set +x
      cd littr.go
      make all
  - tests: |
      set -a +x
      source ~/.env.test
      cd littr.go
      make test
