image: archlinux
packages:
  - go
  - podman
  - buildah
  - aardvark-dns
sources:
  - https://git.sr.ht/~mariusor/brutalinks
secrets:
  - 32610757-76e9-4671-adf1-98163ca8b594
  - 3f30fd61-e33d-4198-aafb-0ff341e9db1c
  - 3dcea276-38d6-4a7e-85e5-20cbc903e1ea
tasks:
  - build: |
      test ${BUILD_SUBMITTER} != "git.sr.ht" && complete-build
      set +x
      cd brutalinks
      make all
  - tests: |
      test ${BUILD_SUBMITTER} != "git.sr.ht" && complete-build
      set -a
      source ~/.env.test
      cd brutalinks
      make test
  - coverage: |
      test ${BUILD_SUBMITTER} != "git.sr.ht" && complete-build
      set -a +x
      cd brutalinks && make coverage
  - push_to_github: |
      test ${BUILD_SUBMITTER} != "git.sr.ht" && complete-build
      set -a +x
      ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      cd brutalinks
      git remote add hub git@github.com:mariusor/go-littr
      git push hub --force --all
  - image: |
      test ${BUILD_SUBMITTER} != "git.sr.ht" && complete-build
      set -a +x
      source ~/.buildah.env

      _user=$(id -un)

      echo 'unqualified-search-registries = ["docker.io"]' | sudo tee /etc/containers/registries.conf.d/unq-search.conf
      echo "${_user}:10000:65536" | sudo tee /etc/subuid
      echo "${_user}:10000:65536" | sudo tee /etc/subgid
      podman system migrate

      podman login -u="${BUILDAH_USER}" -p="${BUILDAH_SECRET}" quay.io

      cd brutalinks || exit

      _sha=$(git rev-parse --short HEAD)
      _branch=$(git branch --points-at=${_sha} | tail -n1 | tr -d '* ')
      _version=$(printf "%s-%s" "${_branch}" "${_sha}")

      make -C images cert builder

      make -C images ENV=dev VERSION="${_version}" push
      if [ "${_branch}" = "master" ]; then
        make -C images ENV=qa VERSION="${_version}" push
      fi
      _tag=$(git describe --long --tags || true)
      if [ -n "${_tag}" ]; then
        make -C images ENV=prod VERSION="${_tag}" push
      fi
  - integration: |
      test ${BUILD_SUBMITTER} != "git.sr.ht" && complete-build
      set -a +x
      source ~/.env.test
      set +a -xe

      cd brutalinks
      make AUTH_IMAGE=quay.io/go-ap/auth:qa FEDBOX_IMAGE=quay.io/go-ap/fedbox:qa-fs integration || podman logs tests_brutalinks tests_fedbox tests_auth



