image: archlinux
packages:
  - go
  - buildah
sources:
  - https://github.com/mariusor/go-littr
environment:
  GO111MODULE: 'on'
secrets:
  - 32610757-76e9-4671-adf1-98163ca8b594
  - 0e431348-6a5c-4404-bd3e-5cdd5ea9e7d6
tasks:
  - build: |
      set +x
      cd go-littr
      make all
  - tests: |
      set -a +x
      source ~/.env.test
      cd go-littr
      make test
  - image: |
      set -a +x
      source ~/.buildah.env && sudo buildah login -u=${BUILDAH_USER} -p=${BUILDAH_SECRET} quay.io
      cd go-littr && sudo make -C docker push
