image: archlinux
packages:
  - go
  - docker
sources:
  - https://github.com/mariusor/go-littr
environment:
  GO111MODULE: 'on'
secrets:
  - 32610757-76e9-4671-adf1-98163ca8b594
  - 3f30fd61-e33d-4198-aafb-0ff341e9db1c
  - 90ecf226-098f-4d66-befe-1fe462027432
tasks:
  - build: |
      set +x
      cd go-littr
      go mod vendor
      make all
  - tests: |
      set -a +x
      source ~/.env.test
      cd go-littr
      make test
  - coverage: |
      set -a +x
      cd go-littr && make coverage
      GIT_SHA=$(git rev-parse --verify HEAD)
      GIT_BRANCH=$(git name-rev --name-only HEAD)
      source ~/.code-cov.sh
      curl -X POST \
          --data-binary @go-littr.coverprofile \
           -H 'Accept: application/json' \
          "https://codecov.io/upload/v2?commit=${GIT_SHA}&token=${LITTR_TOKEN}&branch=${GIT_BRANCH}&service=custom" || true
  - image: |
      set -a +x
      source ~/.buildah.env
      if [ buildah -v dot 2> /dev/null ]; then
        sudo buildah login -u=${BUILDAH_USER} -p=${BUILDAH_SECRET} quay.io
      else
        sudo systemctl start docker.service
        sudo docker login -u=${BUILDAH_USER} -p=${BUILDAH_SECRET} quay.io
      fi
      cd go-littr || exit

      _branch=${GITHUB_REF#"refs/heads/"}
      sudo make -C docker VERSION="${_branch}" push
      if [ "${_branch}" == "master" ]; then
        _branch=$(printf "%s-%s" "${_branch}" "$(git rev-parse --short HEAD)")
        sudo make -C docker ENV=qa VERSION="${_branch}" push
      fi
      _tag=$(git describe --long --tags || true)
      if [ -n "${_tag}" ]; then
        sudo make -C docker ENV=prod VERSION="${_tag}" push
      fi
