image: archlinux
packages:
  - go
  - buildah
sources:
  - https://github.com/mariusor/go-littr
environment:
  GO111MODULE: 'on'
secrets:
  - 32610757-76e9-4671-adf1-98163ca8b594
  - 0e431348-6a5c-4404-bd3e-5cdd5ea9e7d6
tasks:
  - build: |
      set +x
      cd go-littr
      make all
  - tests: |
      set -a +x
      source ~/.env.test
      cd go-littr
      make test
  - image: |
      set -a +x
      source ~/.buildah.env && sudo buildah login -u=${BUILDAH_USER} -p=${BUILDAH_SECRET} quay.io
      cd go-littr || exit

      _branch=${GITHUB_REF#"refs/heads/"}
      sudo make -C docker VERSION="${_branch}" push
      if [ "${_branch}" == "master" ]; then
        _branch=$(printf "%s-%s" "${_branch}" "$(git rev-parse --short HEAD)")
        sudo make -C docker ENV=qa VERSION="${_branch}" push
      fi
      _tag=$(git describe --long --tags || true)
      if [ -n "${_tag}" ]; then
        sudo make -C docker ENV=prod VERSION="${_tag}" push
      fi
