FROM golang:1.13

ARG ENV
ARG PWD

ENV GO111MODULE=on
ENV ENV=${ENV:-dev}

WORKDIR /go/src/
COPY ./ ./app/

RUN git clone https://github.com/go-ap/fedbox.git

WORKDIR /go/src/app
RUN go mod download || true
RUN make all

WORKDIR /go/src/fedbox
RUN go mod download || true
RUN make all
