-- name: extension-pgcrypto
create extension if not exists pgcrypto with schema public;
-- name: extension-ltree
create extension if not exists ltree with schema public;

-- name: create-activitypub-types-enum
CREATE TYPE "types" AS ENUM (
    'Object',
    'Link',
    'Activity',
    'IntransitiveActivity',
    'Actor',
    'Collection',
    'OrderedCollection',
    'CollectionPage',
    'OrderedCollectionPage',
    'Article',
    'Audio',
    'Document',
    'Event',
    'Image',
    'Note',
    'Page',
    'Place',
    'Profile',
    'Relationship',
    'Tombstone',
    'Video',
    'Mention',
    'Application',
    'Group',
    'Organization',
    'Person',
    'Service',
    'Accept',
    'Add',
    'Announce',
    'Arrive',
    'Block',
    'Create',
    'Delete',
    'Dislike',
    'Flag',
    'Follow',
    'Ignore',
    'Invite',
    'Join',
    'Leave',
    'Like',
    'Listen',
    'Move',
    'Offer',
    'Question',
    'Reject',
    'Read',
    'Remove',
    'TentativeReject',
    'TentativeAccept',
    'Travel',
    'Undo',
    'Update',
    'View'
);
